generator_gateway_list: 
 - dagobah
 - tatooine
 - alan1
 - yavin

generator_dagobah_publishers:
  - dagobah_talker

generator_tatooine_publishers:
  - tatooine_talker

generator_alan1_publishers:
  - alan1_talker
  - pr2/wide_stereo/right/image_raw
  - pr2/joint_states
  - pr2/base_scan
  - pr2/tilt_scan
  - pr2/torso_controller/position_joint_action/goal

generator_yavin_publishers:
  - yavin_talker
