
# the gatway list should be the machine name
# the same gatway name should be reflected in your /etc/hosts
generator_gateway_list: 
 - dagobah
 - tatooine
 - pluto
 - alan1
 - yavin

# the demonstration commander machine
generator_commander: dagobah

# pr2 machine name
generator_pr2: alan1

# roman machine name
generator_roman: tatooine # TODO set for roman machine

#list out all action clients the commander needs 
#  5 topics will be generated per the actionlib protocol
#  commander published topics: 'goal', 'cancel'
#  robot published topics: 'status', 'result', 'feedback'
#  
#  These topics will programmatically be added to the generated configs
#  and robot remapping launches (using topic_tools/relay) will also be generated 
#  to correctly assign the robot prefix to conform to the sbpl multimaster convention
generator_commander_action_clients:
  pr2:
    - torso_controller/position_joint_action
    - tf2_buffer_server
    - r_gripper_controller/gripper_action
    - l_gripper_controller/gripper_action
    - head_traj_controller/point_head_action
    - move_base
    - pr2_move_base
    - pr2_move_base_local
    - move_base_local


#list out the servers the commander needs
#  This will add the server to both the robot and commander configs
generator_commander_servers:
  pr2:
    - pr2/tf_lookup_server
  roman:
    - roman/tf_lookup_server



#list out all published topics you want shared on the network
# TODO generate the remapping launch files from the publisher list
generator_alan1_publishers:
  - alan1_talker
  - wide_stereo/right/image_raw
  - joint_states
  - base_scan
  - tilt_scan
  - move_base_simple

generator_dagobah_publishers:
  - dagobah_talker
  
generator_tatooine_publishers:
  - tatooine_talker

generator_yavin_publishers:
  - yavin_talker

generator_pluto_publishers:
  - pluto_talker