watch_loop_period: 1
firewall: false
name: alan1_gateway
network_interface: lan0
default_advertisements:
   - name: /pr2/torso_controller/position_joint_action/status
     node: None
     type: publisher
   - name: /pr2/torso_controller/position_joint_action/result
     node: None
     type: publisher
   - name: /pr2/torso_controller/position_joint_action/feedback
     node: None
     type: publisher
   - name: /pr2/tf_lookup_server
     node: None
     type: server
   - name: /pr2/alan1_talker
     node: None
     type: publisher
   - name: /pr2/wide_stereo/right/image_raw
     node: None
     type: publisher
   - name: /pr2/joint_states
     node: None
     type: publisher
   - name: /pr2/base_scan
     node: None
     type: publisher
   - name: /pr2/tilt_scan
     node: None
     type: publisher

default_pulls:
   - gateway: dagobah_gateway
     rule:
       name: /pr2/torso_controller/position_joint_action/goal
       node: None
       type: subscriber

   - gateway: dagobah_gateway
     rule:
       name: /pr2/torso_controller/position_joint_action/cancel
       node: None
       type: subscriber

   - gateway: dagobah_gateway
     rule:
       name: /dagobah_talker
       node: None
       type: subscriber

   - gateway: tatooine_gateway
     rule:
       name: /roman/tatooine_talker
       node: None
       type: subscriber

   - gateway: yavin_gateway
     rule:
       name: /yavin_talker
       node: None
       type: subscriber

