watch_loop_period: 1
firewall: false
name: alan1_gateway
network_interface: lan0
default_advertisements:
   - name: /alan1_talker
     node: None
     type: publisher
   - name: /pr2/wide_stereo/right/image_raw
     node: None
     type: publisher
   - name: /pr2/joint_states
     node: None
     type: publisher
   - name: /pr2/base_scan
     node: None
     type: publisher
   - name: /pr2/tilt_scan
     node: None
     type: publisher
   - name: /pr2/torso_controller/position_joint_action
     node: None
     type: publisher

default_pulls:
   - gateway: dagobah_gateway
     rule:
       name: /dagobah_talker
       node: None
       type: publisher

   - gateway: tatooine_gateway
     rule:
       name: /tatooine_talker
       node: None
       type: publisher

   - gateway: yavin_gateway
     rule:
       name: /yavin_talker
       node: None
       type: publisher

