watch_loop_period: 1
firewall: false
name: alan1_gateway
network_interface: lan0
default_advertisements:
   - name: /roman_pick_action
     node: None
     type: action_client
   - name: /roman_move_arm
     node: None
     type: action_client
   - name: /roman_grasp_action
     node: None
     type: action_client
   - name: /torso_controller/position_joint_action
     node: None
     type: action_server
   - name: /torso_controller/position_joint_action
     node: None
     type: action_client
   - name: /tf2_buffer_server
     node: None
     type: action_server
   - name: /tf2_buffer_server
     node: None
     type: action_client
   - name: /r_gripper_controller/gripper_action
     node: None
     type: action_server
   - name: /r_gripper_controller/gripper_action
     node: None
     type: action_client
   - name: /l_gripper_controller/gripper_action
     node: None
     type: action_server
   - name: /l_gripper_controller/gripper_action
     node: None
     type: action_client
   - name: /head_traj_controller/point_head_action
     node: None
     type: action_server
   - name: /head_traj_controller/point_head_action
     node: None
     type: action_client
   - name: /move_base
     node: None
     type: action_server
   - name: /move_base
     node: None
     type: action_client
   - name: /pr2_move_base
     node: None
     type: action_server
   - name: /pr2_move_base
     node: None
     type: action_client
   - name: /pr2_move_base_local
     node: None
     type: action_server
   - name: /pr2_move_base_local
     node: None
     type: action_client
   - name: /move_base_local
     node: None
     type: action_server
   - name: /move_base_local
     node: None
     type: action_client
   - name: /pr2/tf_lookup_server
     node: None
     type: service
   - name: /alan1_talker
     node: None
     type: publisher
   - name: /wide_stereo/right/image_raw
     node: None
     type: publisher
   - name: /joint_states
     node: None
     type: publisher
   - name: /base_scan
     node: None
     type: publisher
   - name: /tilt_scan
     node: None
     type: publisher
   - name: /move_base_simple
     node: None
     type: publisher

default_pulls:
   - gateway: dagobah_gateway
     rule:
       name: /roman_pick_action
       node: None
       type: action_server

   - gateway: dagobah_gateway
     rule:
       name: /roman_move_arm
       node: None
       type: action_server

   - gateway: dagobah_gateway
     rule:
       name: /roman_grasp_action
       node: None
       type: action_server

   - gateway: alan1_gateway
     rule:
       name: /torso_controller/position_joint_action
       node: None
       type: action_client

   - gateway: alan1_gateway
     rule:
       name: /torso_controller/position_joint_action
       node: None
       type: action_server

   - gateway: alan1_gateway
     rule:
       name: /tf2_buffer_server
       node: None
       type: action_client

   - gateway: alan1_gateway
     rule:
       name: /tf2_buffer_server
       node: None
       type: action_server

   - gateway: alan1_gateway
     rule:
       name: /r_gripper_controller/gripper_action
       node: None
       type: action_client

   - gateway: alan1_gateway
     rule:
       name: /r_gripper_controller/gripper_action
       node: None
       type: action_server

   - gateway: alan1_gateway
     rule:
       name: /l_gripper_controller/gripper_action
       node: None
       type: action_client

   - gateway: alan1_gateway
     rule:
       name: /l_gripper_controller/gripper_action
       node: None
       type: action_server

   - gateway: alan1_gateway
     rule:
       name: /head_traj_controller/point_head_action
       node: None
       type: action_client

   - gateway: alan1_gateway
     rule:
       name: /head_traj_controller/point_head_action
       node: None
       type: action_server

   - gateway: alan1_gateway
     rule:
       name: /move_base
       node: None
       type: action_client

   - gateway: alan1_gateway
     rule:
       name: /move_base
       node: None
       type: action_server

   - gateway: alan1_gateway
     rule:
       name: /pr2_move_base
       node: None
       type: action_client

   - gateway: alan1_gateway
     rule:
       name: /pr2_move_base
       node: None
       type: action_server

   - gateway: alan1_gateway
     rule:
       name: /pr2_move_base_local
       node: None
       type: action_client

   - gateway: alan1_gateway
     rule:
       name: /pr2_move_base_local
       node: None
       type: action_server

   - gateway: alan1_gateway
     rule:
       name: /move_base_local
       node: None
       type: action_client

   - gateway: alan1_gateway
     rule:
       name: /move_base_local
       node: None
       type: action_server

   - gateway: dagobah_gateway
     rule:
       name: /roman/tf_lookup_server
       node: None
       type: service

   - gateway: alan1_gateway
     rule:
       name: /pr2/tf_lookup_server
       node: None
       type: service

   - gateway: dagobah_gateway
     rule:
       name: /dagobah_talker
       node: None
       type: subscriber

   - gateway: tatooine_gateway
     rule:
       name: /tatooine_talker
       node: None
       type: subscriber

   - gateway: pluto_gateway
     rule:
       name: /pluto_talker
       node: None
       type: subscriber

   - gateway: yavin_gateway
     rule:
       name: /yavin_talker
       node: None
       type: subscriber

   - gateway: kimsk_gateway
     rule:
       name: /kimsk_talker
       node: None
       type: subscriber

