watch_loop_period: 1
firewall: false
name: dagobah_gateway
network_interface: eth0
default_advertisements:
   - name: /roman_pick_action
     node: None
     type: action_server
   - name: /roman_move_arm
     node: None
     type: action_server
   - name: /roman_grasp_action
     node: None
     type: action_server
   - name: /roman/tf_lookup_server
     node: None
     type: service
   - name: /dagobah_talker
     node: None
     type: publisher
   - name: /state_machine
     node: None
     type: service

default_pulls:
   - gateway: alan1_gateway
     rule:
       name: /roman_pick_action
       node: None
       type: action_client

   - gateway: alan1_gateway
     rule:
       name: /roman_move_arm
       node: None
       type: action_client

   - gateway: alan1_gateway
     rule:
       name: /roman_grasp_action
       node: None
       type: action_client

   - gateway: tatooine_gateway
     rule:
       name: /tatooine_talker
       node: None
       type: subscriber

   - gateway: pluto_gateway
     rule:
       name: /pluto_talker
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /alan1_talker
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /wide_stereo/right/image_raw
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /joint_states
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /base_scan
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /tilt_scan
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /move_base_simple
       node: None
       type: subscriber

   - gateway: yavin_gateway
     rule:
       name: /yavin_talker
       node: None
       type: subscriber

   - gateway: kimsk_gateway
     rule:
       name: /kimsk_talker
       node: None
       type: subscriber

