watch_loop_period: 1
firewall: false
name: yavin_gateway
network_interface: eth0
default_advertisements:
   - name: /yavin_talker
     node: None
     type: publisher

default_pulls:
   - gateway: dagobah_gateway
     rule:
       name: /dagobah_talker
       node: None
       type: subscriber

   - gateway: tatooine_gateway
     rule:
       name: /tatooine_talker
       node: None
       type: subscriber

   - gateway: pluto_gateway
     rule:
       name: /pluto_talker
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /alan1_talker
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /wide_stereo/right/image_raw
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /joint_states
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /base_scan
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /tilt_scan
       node: None
       type: subscriber

   - gateway: alan1_gateway
     rule:
       name: /move_base_simple
       node: None
       type: subscriber

